# we manage labels via https://github.com/linuxsuren/linuxsuren-bot-config
repository:
  name: open-source-best-practice
  description: This is an open-source best practice for those who want to participate in open-source projects
  homepage: https://github.com/LinuxSuRen/open-source-best-practice
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      restrictions:
        users: []
        teams: []
